### PR TITLE
Support configuration of Receiver phone number attribute

### PR DESCRIPTION
**Pull request by andrewwgoldmine**
Hi,
I wanted to use the SMS Authenticator with the Smtp2Go SMS API, and of course no two APIs are quite the same!
The only area that couldn't be managed with config settings was that the receiver attribute (destination) needs to be an array rather than a string.
https://developers.smtp2go.com/reference/send-sms-1
```
{
  "destination": [
    "+12025550959"
  ],
  "content": "string"
}
```
Simple enough to resolve for my use - and noticed the similarities with issue #100.

Here I have added a configurable template setting, with the default as "%s" to match existing behaviour.

["%s"] solves for Smtp2Go

{"msisdn": %s} should work for Gateway API

I've made this a template for the Json path only, not sure if a scenario like this exists for URL Encoded cases? If preferred this could be a general template setting for either path I guess.
The other minor update was to use getEnhancedMessages so that realm localisation overrides get picked up.

Seem like a reasonable solution? Thank you for the great plugin.

### CODE REVIEW

**Comment by melegiul** [comment]
Thank you very much for your contribution. I really love your idea. :tada: 

> Here I have added a configurable template setting, with the default as "%s" to match existing behavior.

That sounds like the solution, we are looking for. I will take a closer look and come back to you soon.

**Review by melegiul — APPROVED** [review]
Everything works fine. Thanks again. :smile: 

> I've made this a template for the Json path only, not sure if a scenario like this exists for URL Encoded cases? If preferred this could be a general template setting for either path I guess.

I am not aware of any need for the URL encoded case, too. But as the values can only be alpanumerics I think your proposed solution is just fine as it is.

**Comment by andrewwgoldmine** [comment]
Awesome, thanks! Happy to help, this plugin has been very useful.

**Comment by 123dev** [comment]
> Everything works fine. Thanks again. 😄
> 
> > I've made this a template for the Json path only, not sure if a scenario like this exists for URL Encoded cases? If preferred this could be a general template setting for either path I guess.
> 
> I am not aware of any need for the URL encoded case, too. But as the values can only be alpanumerics I think your proposed solution is just fine as it is.

Thanks for the great plugin, our use case with twilio is URL encoded.
Is it not supported?
https://github.com/netzbegruenung/keycloak-mfa-plugins/issues/202

**Pull request merged**
